name: build
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.2
      - run: zig build

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.2
      - run: zig build fmt

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.2
      - run: zig build test

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.2
      - name: Install kcov
        run: |
          sudo apt-get install -y binutils-dev libssl-dev libcurl4-openssl-dev libelf-dev libstdc++-12-dev zlib1g-dev libdw-dev libiberty-dev cmake
          git clone https://github.com/SimonKagstrom/kcov.git
          cd kcov && git checkout v43 && mkdir build && cd build && cmake .. && make && sudo make install
      - run: zig build cov
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          file: .coverage/test/cov.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
